import Head from "next/head";
import { GetStaticProps } from "next";
import WeatherApp from "../components/WeatherApp";
import { weatherType } from "../interfaces_&_funcs/interfaces";
import { useEffect, useState } from "react";
import {
  initDataFetch,
  getWeatherData,
  getNewWeather,
} from "../interfaces_&_funcs/data_fetch_funcs";

export const getStaticProps: GetStaticProps = async () => {
  const locationInfo = await initDataFetch();
  const initWeatherData = await getWeatherData(locationInfo);
  return {
    props: {
      initWeatherData,
    },
  };
};

export default function Home(props: { initWeatherData: weatherType }) {
  const [location, setlocation] = useState("london");
  const [weatherData, setWeatherData] = useState(props.initWeatherData);
  useEffect(() => {
    getNewWeather(location).then((res) => setWeatherData(res));
  }, [location]);
  return (
    <>
      <Head>
        <title>the.weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WeatherApp
        weatherData={weatherData}
        setlocation={(loc) => {
          setlocation(loc);
        }}
      />
    </>
  );
}
